version: "3"
services:
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    volumes:
      - ./gateway:/usr/src/app
    command: npm start
  auth:
    build: ./auth
    ports:
      - "8001:8001"
    volumes:
      - ./auth:/usr/src/app
    command: npm start
