name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  run-tests:
    env:
      PORT: 3000

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          cd gateway
          npm install

      - name: Lint
        run: |
          cd gateway
          npm run lint

      - name: Format
        run: |
          cd gateway
          npm run format

      - name: build and test
        run: |
          cd gateway
          npm run build --if-present
          npm test
